### ISSUE TITLE
Won't build on ubuntu 16.04

### ISSUE THREAD

**Issue by mraaroncruz** [dystophia/VeoCL#1]
I had to change the `Makefile` to read:

```Makefile
clientnvidia:   $(dependencies)
        gcc -o clientnvidia -L/usr/local/cuda/lib64 $(inputFiles) -D'CLWAIT=1' $(compileOptions)
```
It couldn't find my libOpenCL.so

**Comment by dystophia** [comment]
sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/x86_64-linux-gnu/libOpenCL.so

**Comment by mraaroncruz** [comment]
Thanks. Maybe add to Readme?

**Comment by dystophia** [comment]
Done.
